// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SltUtilServiceClient is the client API for SltUtilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SltUtilServiceClient interface {
	// hello
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
}

type sltUtilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSltUtilServiceClient(cc grpc.ClientConnInterface) SltUtilServiceClient {
	return &sltUtilServiceClient{cc}
}

func (c *sltUtilServiceClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, "/api.SltUtilService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SltUtilServiceServer is the server API for SltUtilService service.
// All implementations must embed UnimplementedSltUtilServiceServer
// for forward compatibility
type SltUtilServiceServer interface {
	// hello
	Hello(context.Context, *HelloReq) (*HelloResp, error)
	mustEmbedUnimplementedSltUtilServiceServer()
}

// UnimplementedSltUtilServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSltUtilServiceServer struct {
}

func (UnimplementedSltUtilServiceServer) Hello(context.Context, *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedSltUtilServiceServer) mustEmbedUnimplementedSltUtilServiceServer() {}

// UnsafeSltUtilServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SltUtilServiceServer will
// result in compilation errors.
type UnsafeSltUtilServiceServer interface {
	mustEmbedUnimplementedSltUtilServiceServer()
}

func RegisterSltUtilServiceServer(s grpc.ServiceRegistrar, srv SltUtilServiceServer) {
	s.RegisterService(&SltUtilService_ServiceDesc, srv)
}

func _SltUtilService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltUtilServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SltUtilService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltUtilServiceServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SltUtilService_ServiceDesc is the grpc.ServiceDesc for SltUtilService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SltUtilService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SltUtilService",
	HandlerType: (*SltUtilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _SltUtilService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/svc.proto",
}
